name: Update ROTMG
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  RotmgUpdate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Cleanup
      run: rm decompiled -rf *

    - name: Download JPEXS
      run: |
        cd $HOME
        wget https://github.com/jindrapetrik/jpexs-decompiler/releases/download/version11.3.0/ffdec_11.3.0.zip -O ffdec.zip
        
        unzip ffdec.zip
        
    - name: Download latest client
      run: wget https://www.realmofthemadgod.com/client -O client.swf
      
    - name: Decompile client
      run: |
        # Scripts
        java -jar $HOME/ffdec.jar -export script decompiled client.swf
        java -jar $HOME/ffdec.jar -format script:pcode -export script decompiled client.swf
        # Binary data
        java -jar $HOME/ffdec.jar -export binaryData decompiled/data client.swf
        
    - name: Download version.txt
      run: wget https://www.realmofthemadgod.com/version.txt
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Automatic] ROTMG Client update"
