name: Update ROTMG
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  RotmgUpdate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Cleanup
      run: rm decompiled xml xmlc json -rf

    - name: Download JPEXS
      run: |
        cd $HOME
        wget https://github.com/jindrapetrik/jpexs-decompiler/releases/download/version11.3.0/ffdec_11.3.0.zip -O ffdec.zip
        
        unzip ffdec.zip
        
    - name: Download latest client
      run: wget https://www.realmofthemadgod.com/client -O client.swf
      
    - name: Decompile client
      run: |
        # Scripts
        java -jar $HOME/ffdec.jar -export script decompiled client.swf
        java -jar $HOME/ffdec.jar -format script:pcode -export script decompiled client.swf
        
        # Binary data
        java -jar $HOME/ffdec.jar -export binaryData decompiled/data client.swf
        
    - name: Download other things
      run: |
        # Version
        wget https://www.realmofthemadgod.com/version.txt -O version.txt

        # xml and json files
        wget -r -nH --cut-dirs=3 --no-parent --reject="index.html*" -e robots=off https://static.drips.pw/rotmg/production/current/xml/
        wget -r -nH --cut-dirs=3 --no-parent --reject="index.html*" -e robots=off https://static.drips.pw/rotmg/production/current/xmlc/
        wget -r -nH --cut-dirs=3 --no-parent --reject="index.html*" -e robots=off https://static.drips.pw/rotmg/production/current/json/

        # Other
        wget https://static.drips.pw/rotmg/production/current/init.json    -O init.json
        wget https://static.drips.pw/rotmg/production/current/strings.json -O strings.json
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Automatic] ROTMG Client update"
