name: Update ROTMG
on: [push]
  #schedule:
   # - cron: "*/5 * * * *"

jobs:
  RotmgUpdate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Cleanup
      run: rm -rf *        

    - name: Download JPEXS
      run: |
        cd $HOME
        wget https://github.com/jindrapetrik/jpexs-decompiler/releases/download/version11.3.0/ffdec_11.3.0.zip -O ffdec.zip
        
        unzip ffdec.zip
        
    - name: Download latest client
      run: wget https://www.realmofthemadgod.com/client -O client.swf
      
    - name: Decompile client
      run: | 
        java -jar $HOME/ffdec.jar -export script decompiled/as client.swf
        java -jar $HOME/ffdec.jar -format script:pcode -export script decompiled/pcode client.swf
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated ROTMG client
