name: Update ROTMG
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  RotmgUpdate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Cleanup
      run: rm decompiled -rf

    - name: Download JPEXS
      run: |
        cd $HOME
        wget https://github.com/jindrapetrik/jpexs-decompiler/releases/download/version11.3.0/ffdec_11.3.0.zip -O ffdec.zip
        
        unzip ffdec.zip
        
    - name: Download latest client
      run: wget https://www.realmofthemadgod.com/client -O client.swf
      
    - name: Decompile client
      run: |
        # Scripts
        java -jar $HOME/ffdec.jar -export script decompiled client.swf
        java -jar $HOME/ffdec.jar -format script:pcode -export script decompiled client.swf
        # Binary data
        java -jar $HOME/ffdec.jar -export binaryData decompiled/data client.swf
        
    - name: Download other things
      run: |
        # Version
        wget https://www.realmofthemadgod.com/version.txt -O version.txt

        # combined xml files
        wget https://static.drips.pw/rotmg/production/current/xmlc/Dungeons.xml      -O xmlc/Dungeons.xml
        wget https://static.drips.pw/rotmg/production/current/xmlc/EquipmentSets.xml -O xmlc/EquipmentSets.xml
        wget https://static.drips.pw/rotmg/production/current/xmlc/GroundTypes.xml   -O xmlc/GroundTypes.xml
        wget https://static.drips.pw/rotmg/production/current/xmlc/Objects.xml       -O xmlc/Objects.xml
        wget https://static.drips.pw/rotmg/production/current/xmlc/Particles.xml     -O xmlc/Particles.xml
        wget https://static.drips.pw/rotmg/production/current/xmlc/Regions.xml       -O xmlc/Regions.xml
        wget https://static.drips.pw/rotmg/production/current/xmlc/Tutorial.xml      -O xmlc/Tutorial.xml

        # Combined json files
        wget https://static.drips.pw/rotmg/production/current/json/Dungeons.json      -O json/Dungeons.json
        wget https://static.drips.pw/rotmg/production/current/json/EquipmentSets.json -O json/EquipmentSets.json
        wget https://static.drips.pw/rotmg/production/current/json/GroundTypes.json   -O json/GroundTypes.json
        wget https://static.drips.pw/rotmg/production/current/json/Objects.json       -O json/Objects.json
        wget https://static.drips.pw/rotmg/production/current/json/Particles.json     -O json/Particles.json
        wget https://static.drips.pw/rotmg/production/current/json/Regions.json       -O json/Regions.json
        wget https://static.drips.pw/rotmg/production/current/json/Tutorial.json      -O json/Tutorial.json

        # Other
        wget https://static.drips.pw/rotmg/production/current/init.json    -O init.json
        wget https://static.drips.pw/rotmg/production/current/strings.json -O strings.json
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Automatic] ROTMG Client update"
